
name: Build iOS

on:
  [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build iOS
        run: |
          ln -s vulkan_ios.pc vulkan.pc
          brew install meson pkg-config
          pip3 install mako
          meson setup "build-ios-aarch64" \
            --prefix=/tmp/asahi \
            --cross-file "ios-aarch64" \
            -Db_lundef=false \
            -Dllvm=disabled \
            -Dxlib-lease=disabled \
            -Degl=disabled \
            -Dgbm=disabled \
            -Dglx=disabled \
            -Dopengl=true \
            -Dosmesa=true \
            -Dvulkan-drivers= \
            -Dgallium-drivers=asahi \
            -Dshared-glapi=false \
            -Dbuildtype=release
          ninja -C "build-android" install
          cp -r build-ios-aarch64/src/gallium/drivers/asahi /tmp/
      - name: Upload libraries
        uses: actions/upload-artifact@v2
        with:
          name: libOSMesa
          path: /tmp/asahi